### ISSUE TITLE
異臭issue

### ISSUE THREAD

**Issue by s7ez** [cet-t/selfgamelib#1]
```cpp
#include <iostream>
// #include <cstring>
#include <string.h>

using namespace std;

void randchar(char *out_, const int length_);

int main() {
    char output[27];
    randchar(output, 27);
    // cout << output << endl;

    return 0;
}

void randchar(char *out_, const int length_) {
    char *alphabets = new char[27];
    char *a = new char[27];
    strncpy(alphabets, "abcdefghijklmnopqrstuvwxyz\0", 27);
    strncpy(out_, alphabets, length_);
    // strncpy(a, alphabets, 27);
    a = strdup("aiu");
    cout << a << endl;
    
    delete[] alphabets, a;
}
```

**Comment by s7ez** [comment]
// Online C++ compiler to run C++ program online
#include <iostream>
// #include <cstring>
#include <string.h>

using namespace std;

void randchar(char *out_, const int length_);

int main() {
    // char output[27];
    // randchar(output, 27);
    // cout << output << endl;
    const char alphabets[27] = {"abcdefghijklmnopqrstuvwxyz"},
        numbers[11] = {"0123456789"};
    char *a = new char[27+11];
    strcat(a, alphabets);
    strcat(a, numbers);
    cout << a << endl;
    delete[] a;
    
    return 0;
}

void randchar(char *out_, const int length_) {
    char *alphabets = new char[27];
    char *a = new char[27];
    strncat(alphabets, "abcdefghijklmnopqrstuvwxyz\0", 27);
    strncat(out_, alphabets, length_);
    // strncpy(a, alphabets, 27);
    a = strdup("aiu");
    cout << a << endl;
    
    delete[] alphabets, a;
}

**Comment by s7ez** [comment]
finish

```cpp
#include <iostream>
#include <string.h>
#include <random>
#include <chrono>
#include <math.h>

using namespace std;
using namespace std::chrono;

#define ALPHABET (26+1)
#define NUMBER (10+1)

float randuniform(float min_, float max_ex_);
int randint(int min_, int max_ex_);
void randchar(char *out_, const int length_);

int main() {
    const int LENGTH = 20;
    char output[LENGTH];
    randchar(output, LENGTH);
    cout << output << endl;
    
    return 0;
}

float randuniform(float min_, float max_ex_)
{
    system_clock::duration now = system_clock::now().time_since_epoch();
    system_clock::rep ns = duration_cast<nanoseconds>(now).count();
    mt19937_64 mt64(ns);
    uniform_real_distribution<float> r(min_, max_ex_ - 1);
    return r(mt64);
}

int randint(int min_, int max_ex_)
{
    auto uniform = randuniform(min_, max_ex_ - 1);
    return (int)floorf(uniform);
}

void randchar(char *out_, const int length_) {
    const char alphabets[ALPHABET] = {"abcdefghijklmnopqrstuvwxyz"},
        numbers[NUMBER] = {"0123456789"};
    char *a = new char[27];
    strncat(a, alphabets, ALPHABET);
    strncat(a, numbers, NUMBER);
    char dst[length_];
    for (int i = 0; i < length_; ++i) {
        dst[i] = a[randint(0, ALPHABET+NUMBER-1)];
    }
    strncpy(out_, dst, length_);
    out_[length_-1] = '\0';
    
    delete[] a;
}
```

**Comment by cet-t** [comment]
#include <iostream>
#include <string.h>
#include <random>
#include <chrono>
#include <math.h>

using namespace std;
using namespace std::chrono;

#define ALPHABET 26
#define NUMBER 10

float randuniform(float min_, float max_ex_);
int randint(int min_, int max_ex_);
void randchar(char *out_, const int length_);

int main() {
    const int LENGTH = 20;
    // for (int i = 0; i < 10; ++i) {
        char output[LENGTH];
        randchar(output, LENGTH);
        cout << output << endl;
    // }
    
    return 0;
}

float randuniform(float min_, float max_ex_)
{
    system_clock::duration now = system_clock::now().time_since_epoch();
    system_clock::rep ns = duration_cast<nanoseconds>(now).count();
    mt19937_64 mt64(ns);
    uniform_real_distribution<float> r(min_, max_ex_ - 1);
    return r(mt64);
}

int randint(int min_, int max_ex_)
{
    auto uniform = randuniform(min_, max_ex_ - 1);
    return (int)floorf(uniform);
}

void randchar(char *out_, const int length_) {
    const char alphabets[ALPHABET+1] = {"abcdefghijklmnopqrstuvwxyz"},
        numbers[NUMBER+1] = {"0123456789"};
    char *a = new char[ALPHABET+1];
    strncat(a, alphabets, ALPHABET+1);
    strncat(a, numbers, NUMBER+1);
        for (int i = 0; i < ALPHABET + NUMBER + 1; ++i)
        cout << i << ": " << a[i] << endl;
    char dst[length_];
    for (int i = 0; i < length_; ++i) {
        dst[i] = a[randint(0, ALPHABET+NUMBER)];
    }
    dst[length_] = '\0';
    strncpy(out_, dst, length_);
    out_[length_-1] = '\0';
    
    delete[] a;
}

**Comment by s7ez** [comment]
#include <iostream>
#include <string.h>

using namespace std;

#define ALPHABET 26
#define NUMBER 10

void rchar(char *out_, const int length_) noexcept {
    constexpr char alphabet[ALPHABET+1] = {"abcdefghijklmnopqrstuvwxyz"};
    constexpr char number[NUMBER+1] = {"0123456789"};
    strncat(out_, alphabet, ALPHABET);
    strncat(out_, number, NUMBER);
    out_[length_-1] = '\0';
}

int main() {
    char out[ALPHABET+NUMBER+1];
    rchar(out, ALPHABET+NUMBER+1);
    cout << out << endl;
    
    return 0;
}
